-- 论坛系统数据库表结构
-- 创建时间：2026年7月4日

-- 论坛分类表
CREATE TABLE IF NOT EXISTS forum_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, -- 分类名称：资源分享、学习讨论、反馈建议等
  description TEXT, -- 分类描述
  slug TEXT UNIQUE NOT NULL, -- URL友好的分类标识
  sort_order INTEGER DEFAULT 0, -- 排序权重
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  is_active BOOLEAN DEFAULT true -- 是否启用
);

-- 论坛帖子表
CREATE TABLE IF NOT EXISTS forum_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL, -- 帖子标题
  content TEXT NOT NULL, -- 帖子内容
  summary TEXT, -- 内容摘要
  category_id BIGINT REFERENCES forum_categories(id) ON DELETE SET NULL,
  author_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  post_type TEXT NOT NULL DEFAULT 'discussion', -- 帖子类型：discussion, resource, feedback
  resource_type TEXT, -- 资源类型：video, audio, article, document
  resource_url TEXT, -- 资源链接（用户提供的资源地址）
  resource_description TEXT, -- 资源描述
  tags TEXT[], -- 标签数组
  view_count INTEGER DEFAULT 0, -- 浏览量
  like_count INTEGER DEFAULT 0, -- 点赞数
  comment_count INTEGER DEFAULT 0, -- 评论数
  is_featured BOOLEAN DEFAULT false, -- 是否推荐
  is_pinned BOOLEAN DEFAULT false, -- 是否置顶
  status TEXT DEFAULT 'published', -- 状态：draft, published, moderating, rejected
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  published_at TIMESTAMPTZ,
  moderated_at TIMESTAMPTZ,
  moderator_id UUID REFERENCES auth.users(id)
);

-- 帖子封面图片（使用Supabase Storage）
CREATE TABLE IF NOT EXISTS post_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES forum_posts(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL, -- Supabase Storage中的图片URL
  image_type TEXT DEFAULT 'cover', -- 图片类型：cover, content
  alt_text TEXT, -- 图片描述
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 帖子和资源点赞表
CREATE TABLE IF NOT EXISTS forum_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  post_id BIGINT REFERENCES forum_posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, post_id) -- 防止重复点赞
);

-- 论坛评论表
CREATE TABLE IF NOT EXISTS forum_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES forum_posts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  parent_id BIGINT REFERENCES forum_comments(id) ON DELETE CASCADE, -- 支持回复评论
  content TEXT NOT NULL,
  like_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'published', -- published, moderating, rejected
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  moderated_at TIMESTAMPTZ,
  moderator_id UUID REFERENCES auth.users(id)
);

-- 评论点赞表
CREATE TABLE IF NOT EXISTS comment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES forum_comments(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, comment_id)
);

-- 用户收藏表
CREATE TABLE IF NOT EXISTS user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  post_id BIGINT REFERENCES forum_posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, post_id)
);

-- 论坛通知表
CREATE TABLE IF NOT EXISTS forum_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 通知类型：like, comment, reply, mention
  title TEXT NOT NULL,
  content TEXT,
  post_id BIGINT REFERENCES forum_posts(id),
  comment_id BIGINT REFERENCES forum_comments(id),
  from_user_id UUID REFERENCES auth.users(id),
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 反馈和建议表
CREATE TABLE IF NOT EXISTS user_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  feedback_type TEXT NOT NULL, -- bug, feature, content, general
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  priority TEXT DEFAULT 'medium', -- low, medium, high, urgent
  status TEXT DEFAULT 'open', -- open, in_progress, resolved, closed
  admin_response TEXT,
  admin_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

-- 用户论坛配置表
CREATE TABLE IF NOT EXISTS user_forum_preferences (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email_notifications BOOLEAN DEFAULT true, -- 邮件通知
  push_notifications BOOLEAN DEFAULT true, -- 推送通知
  show_email BOOLEAN DEFAULT false, -- 公开邮箱
  bio TEXT, -- 个人简介
  signature TEXT, -- 签名档
  avatar_url TEXT, -- 头像URL
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 论坛统计表（定期更新）
CREATE TABLE IF NOT EXISTS forum_stats (
  id INTEGER PRIMARY KEY DEFAULT 1,
  total_posts INTEGER DEFAULT 0,
  total_comments INTEGER DEFAULT 0,
  total_users INTEGER DEFAULT 0,
  active_users_week INTEGER DEFAULT 0,
  active_users_month INTEGER DEFAULT 0,
  last_updated TIMESTAMPTZ DEFAULT now()
);

-- 插入默认分类
INSERT INTO forum_categories (name, description, slug, sort_order) VALUES
('资源分享', '分享视频、音频、文章等学习资源', 'resources', 1),
('学习讨论', '学习方法、经验交流和问题讨论', 'discussion', 2),
('反馈建议', '应用bug反馈、功能建议', 'feedback', 3),
('学习互助', '学习问题求助和互助', 'help', 4),
('学习小组', '组建和管理学习小组', 'groups', 5)
ON CONFLICT (name) DO NOTHING;

-- 插入默认统计数据
INSERT INTO forum_stats DEFAULT VALUES ON CONFLICT DO NOTHING;

-- 启用RLS（行级安全）
ALTER TABLE forum_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_forum_preferences ENABLE ROW LEVEL SECURITY;

-- forum_categories 策略：所有人可读取，只有管理员可修改
CREATE POLICY "Everyone can read categories" ON forum_categories
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admin can manage categories" ON forum_categories
  FOR ALL USING (auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

-- forum_posts 策略
CREATE POLICY "Everyone can read published posts" ON forum_posts
  FOR SELECT USING (status = 'published');

CREATE POLICY "Users can create posts" ON forum_posts
  FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update own posts" ON forum_posts
  FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Admins can moderate posts" ON forum_posts
  FOR ALL USING (auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

-- post_images 策略
CREATE POLICY "Everyone can read post images" ON post_images
  FOR SELECT USING (true);

CREATE POLICY "Users can manage own post images" ON post_images
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM forum_posts 
      WHERE forum_posts.id = post_images.post_id 
      AND forum_posts.author_id = auth.uid()
    )
  );

-- forum_likes 策略
CREATE POLICY "Everyone can read likes" ON forum_likes
  FOR SELECT USING (true);

CREATE POLICY "Users can create likes" ON forum_likes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own likes" ON forum_likes
  FOR DELETE USING (auth.uid() = user_id);

-- forum_comments 策略
CREATE POLICY "Everyone can read published comments" ON forum_comments
  FOR SELECT USING (status = 'published');

CREATE POLICY "Users can create comments" ON forum_comments
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own comments" ON forum_comments
  FOR UPDATE USING (auth.uid() = user_id);

-- comment_likes 策略
CREATE POLICY "Everyone can read comment likes" ON comment_likes
  FOR SELECT USING (true);

CREATE POLICY "Users can create comment likes" ON comment_likes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own comment likes" ON comment_likes
  FOR DELETE USING (auth.uid() = user_id);

-- user_favorites 策略
CREATE POLICY "Users can read own favorites" ON user_favorites
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own favorites" ON user_favorites
  FOR ALL USING (auth.uid() = user_id);

-- forum_notifications 策略
CREATE POLICY "Users can read own notifications" ON forum_notifications
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own notifications" ON forum_notifications
  FOR UPDATE USING (auth.uid() = user_id);

-- user_feedback 策略
CREATE POLICY "Users can read own feedback" ON user_feedback
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create feedback" ON user_feedback
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can manage all feedback" ON user_feedback
  FOR ALL USING (auth.uid() IN (
    SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
  ));

-- user_forum_preferences 策略
CREATE POLICY "Users can manage own preferences" ON user_forum_preferences
  FOR ALL USING (auth.uid() = user_id);

-- 添加supabase_realtime发布（如果还不存在）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'forum_posts'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_posts;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'forum_comments'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_comments;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemanane = 'public'
      AND tablename = 'forum_notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.forum_notifications;
  END IF;
END $$;

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_forum_posts_category ON forum_posts(category_id);
CREATE INDEX IF NOT EXISTS idx_forum_posts_author ON forum_posts(author_id);
CREATE INDEX IF NOT EXISTS idx_forum_posts_created ON forum_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_forum_posts_status ON forum_posts(status);
CREATE INDEX IF NOT EXISTS idx_forum_posts_type ON forum_posts(post_type);
CREATE INDEX IF NOT EXISTS idx_forum_posts_featured ON forum_posts(is_featured);
CREATE INDEX IF NOT EXISTS idx_forum_posts_pinned ON forum_posts(is_pinned);

CREATE INDEX IF NOT EXISTS idx_forum_comments_post ON forum_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_forum_comments_user ON forum_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_forum_comments_parent ON forum_comments(parent_id);

CREATE INDEX IF NOT EXISTS idx_forum_likes_post ON forum_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_forum_likes_user ON forum_likes(user_id);

CREATE INDEX IF NOT EXISTS idx_forum_notifications_user ON forum_notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_forum_notifications_read ON forum_notifications(is_read);

CREATE INDEX IF NOT EXISTS idx_user_favorites_user ON user_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_post ON user_favorites(post_id);